clc;clear;close all;
data = load('tmp_data/cpwmodel_all_spacescalable.mat');
cpwmodel_space = data.cpwmodel_all;clear data;

err_struct_unit  = get_errors_unit_length( cpwmodel_space.scalable_space_model );
err_struct_unit.var = [cpwmodel_space.scalable_space_model.space]*1e6;

%% plot error of RLGC
plot_err_RLGC( err_struct_unit.ave_err_RLGC,err_struct_unit.max_err_RLGC,...
               err_struct_unit.var,'space [\mum]','Error of RLGC-Scalable')
%% plot error of gamma and Z           
ave_err_g_z = [err_struct_unit.ave_err_alpha;...
               err_struct_unit.ave_err_beta;...
               err_struct_unit.ave_err_Z_real;...
               err_struct_unit.ave_err_Z_imag];
       
max_err_g_z = [err_struct_unit.max_err_alpha;...
               err_struct_unit.max_err_beta;...
               err_struct_unit.max_err_Z_real;...
               err_struct_unit.max_err_Z_imag];
plot_err_gamma_Z( ave_err_g_z,max_err_g_z,...
                err_struct_unit.var,'space [\mum]','Error of Gamma & Z -Scalable')


